CXXFLAGS := --std=c++17 -g -O0 -m32 -fno-use-cxa-atexit \
	    -nostdlib -fno-builtin -fno-rtti -fno-exceptions \
	    -fno-leading-underscore
ASFLAGS := --32
LDFLAGS := -melf_i386 -T $(DIR)/linker.ld

